### ISSUE TITLE
Incorrect redering of character on Risk Dashboard

### ISSUE THREAD

**Issue by boylesean** [simplerisk/bundles#12]
Rather than displaying "Owner's Manager", "Owner&#039;s Manager" is displayed.

![screenshot from 2015-01-22 12 38 41](https://cloud.githubusercontent.com/assets/9705580/5864087/c1fe0d62-a233-11e4-809b-07dedc5ae51d.png)

**Comment by jsokol** [comment]
I have actually tried to fix this particular issue several times in the code.  The problem is that the value of "Owner's Manager" is getting pulled from the language file.  In order to ensure that someone can't place malicious code in there, I perform HTML encoding on the value.  But....the javascript library that renders these graphs doesn't display it as encoded as you can see and I can't find an encoder that will work properly here.  If it bugs you, you can update your language file to remove the apostrophe and it will no longer be displayed like this.  It may be a while before I attempt to find another way to fix this as it is purely aesthetic and this is the only place you'll see it happen.

**Comment by jsokol** [comment]
This issue has been corrected.
