### ISSUE TITLE
Install issues with last version (stuck at database check)

### ISSUE THREAD

**Issue by tespio** [simplerisk/bundles#25]
To whom it may concern

Trying to install simplerisk today using simplerisk-20210305-001.tgz and simplerisk-installer-20210305-001.tgz. I pass the first install check (modules and ownership of files) and i'm being asked the mysql db host/port/user/pass. However i get an error no matter what php version i try (i tested with 7.0/7.1/7.3/8.0) 
With 7.x i get:
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /path/obfuscated/install/index.php on line 274
With 8.0 i get:
PHP message: PHP Warning:  foreach() argument must be of type array|object, string given in /path/obfuscated/install/index.php on line 274

Any advice how to i get past database check step in the install folder?
Thank you in advance

Andy

**Comment by jsokol** [comment]
Hey Andy!  What OS are you using to do this installation?  We tested the installation script prior to release and it worked fine.  We haven't had any other users complain and have had a number of successful installations and registrations over the past two months since that release.

If I had to guess, I'd say that you didn't place the install directory inside the simplerisk directory and that is why you're receiving this error.  It should go /path/obfuscated/simplerisk/install.  Can you please confirm this is what you are doing?

**Comment by tespio** [comment]
HI Josh

I am installing it on a Debian 10 under nginx/php-fastcgi. But i don't think it's an issue with the location of the install script. I have created a vhost in nginx like risk.domain.com and in the root directory of the vhost i have unpacked simplerisk-20210305-001.tgz. Then i unpacked the simplerisk-installer-20210305-001.tgz into the same root directory of the vhost. So, since i am not working with a subdirectory, it doesn't make sense to place install/ folder into simplerisk subfolder while all the simplerisk core files are also in the root dir of the vhost. Am i wrong? (I've been a linux system administrator for the past 17 years so i have some knowledge in the field).
Thank you for your time.
Andy

**Comment by tespio** [comment]
Since the timezone difference between us is quite big i will try my luck and attempt a manual install. I'll directly import the simplerisk-en* schema. I'll have to see how i will create the unique salt and generate the password hash for the admin user. the simplerisk base url insert should be fairly simple to do. config.php in includes/ dir is already configured.

Regards
Andy

**Comment by tespio** [comment]
Hi Josh

I have managed to manually installed (as explained above and everything runs just fine). Thank you for your time and patience!

Regards
Andy

PS: I still think there is an issue in the installation script at line 247 as outlined above. I'm just not sure what it is (i'm not a programmer :D )

**Comment by jsokol** [comment]
Andy,

Yes, I don't mean to be rude here, but you are wrong. Our instructions explicitly state to place the install directory inside of the simplerisk directory. This is because it utilizes files from the simplerisk directory for the health check. And, in your case, the health check is what is failing. You would then either point your web root to the simplerisk directory (ie. Run it under /) and use https://domain/install as the install path or, based on what you said, use https://domain/simplerisk/install.

Glad to hear that your manual import worked. Hopefully you looked through the install script and did the various checks to ensure that everything else is set up properly and installed the user account with the proper permissions, as well. If not, I would highly recommend starting over and closely following our installation instructions so that you wind up with a properly working instance.

**Comment by tespio** [comment]
Hi Josh

Maybe i didn't explained well, but my equivalent for "simplerisk" directory is the root dir of the subdomain vhost. So in this case it makes sense that all simplerisk core files should go into the / of the subdomain site (in my case risk.somedomain.com - physical path is something like /var/www/vhosts/risk.somedomain.com/), therefore i unpacked the installer folder in the path mentioned before. So when i access in my browser https://risk.somedomain.com/install i actually find the installer files (and the installer finds the dependencies in the core files one directory behind (realpath(__DIR__ . "/../").

Anyway yeah, as you said i managed to install it with manual import. So far i've checked all the settings and everything seems fine (i've registered the instance with simplerisk.com and downloaded the ComplianceForge SCF extras etc.
What i don't understand is about mysql health check. Since the server simplerisk is running on hosts several other databases for other sites, i don't find it normal to grant global privileges to the db user used by simplerisk. It has all privileges over the DB of simplerisk install and that should be enough. So i get some warnings in there but they don't seem to interfere with the soft operation overall.
![image](https://user-images.githubusercontent.com/22332699/117452472-7a599a80-af4c-11eb-92ee-80aed4c523bc.png)

Anyway thanks again for your time. 
Kindest Regards
Andy

**Comment by jsokol** [comment]
Andy,

I provisioned a Debian 10 system and did some testing.  I figured that since I already had to run the commands to get it installed and working, I'd just add it to our bash setup script.  So now the entire provisioning process on a fresh Debian 10 system will work with a single command:

`curl -sL https://raw.githubusercontent.com/simplerisk/setup-scripts/master/simplerisk-setup.sh | bash -`

After running through this installation you should have a fully operational SimpleRisk instance on Debian 10 which passes all appropriate health checks.  It configures SSL for you, but uses a self-signed SSL certificate.  MariaDB is the database that I used here.  I cannot vouch for Percona as a database that will work or that we can support, but we have a number of instances running MariaDB with no issues.  Based on the issues you've experienced, I'd highly recommend starting over with this installation script.

Now, for testing purposes, after I ran this installation I went ahead and deleted my simplerisk database and the user permissions associated with it.  I then downloaded the installer and extracted it under /var/www/simplerisk which created the /var/www/simplerisk/install directory.  From there, I hit https://domain/install and ran through the installer with no issues.  I can conclusively say that, if everything else is configured properly, there are no issues with the SimpleRisk database installer running on Debian 10.
