### ISSUE TITLE
Install on shared host

### ISSUE THREAD

**Issue by runsy** [simplerisk/bundles#26]
I have not he root password of my shared host. How can I install it?

Note: I manually edited the config.php file too, to try.

The error log:

> [09-Jul-2021 23:09:44 UTC] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in /home/ohsc1orckkh1/public_html/simplerisk/includes/permissions.php:26
> Stack trace:
> #0 /home/ohsc1orckkh1/public_html/simplerisk/includes/permissions.php(168): table_exists('permissions')
> #1 /home/ohsc1orckkh1/public_html/simplerisk/includes/permissions.php(43): get_possible_permissions()
> #2 /home/ohsc1orckkh1/public_html/simplerisk/includes/authenticate.php(12): require_once('/home/ohsc1orck...')
> #3 /home/ohsc1orckkh1/public_html/simplerisk/includes/functions.php(13): require_once('/home/ohsc1orck...')
> #4 /home/ohsc1orckkh1/public_html/simplerisk/index.php(7): require_once('/home/ohsc1orck...')
> #5 {main}
>   thrown in /home/ohsc1orckkh1/public_html/simplerisk/includes/permissions.php on line 26

**Comment by runsy** [comment]
Finally I solved getting the SQL file from the install. Then I made a SQL exec in phpmyadmin to fill the database. And it works.

My concern:

Simple risk does not support shared host (simple risk does not install on a already created database)

**Comment by jsokol** [comment]
Hello!  We do not typically have customers installing SimpleRisk on a shared hosting provider.  Technically speaking, you should be able to user the installer to install it just fine as long as the user account you have for MySQL has the permissions to create additional users and assign them permissions.  I'm guessing you don't, however, based on your comment that you don't have the root password.  In that case, manually doing a database import should be fine and you can find the database schemas in this repo:

https://github.com/simplerisk/database

But your user needs to have SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEXES and REFERENCES permissions for the application to work properly.

I appreciate your concerns, but we do not intend to make any changes to the application in order to support shared hosting.  This is an application designed for storing sensitive risk data and the idea of it running on a shared hosting provider is fairly concerning to me.  

As for installing only filling in the data of the config.php, this would bypass the health checks in the installer and could create other issues down the line.  We would much prefer to validate the environment before moving forward with an installation.  

Your situation is a bit of an edge case and, fortunately, I can say that this is the first time anyone has reached out with this concern.  We'll keep an eye on it, so thank you for reporting, but for now we will not be making any changes.
